### PR TITLE
Add a few more links to community projects

### PR DESCRIPTION
**Pull request by leofang**
cc: @rgommers @tirthasheshpatel

### CODE REVIEW

**Review by tirthasheshpatel — APPROVED** [review]
All the links look good to me, thanks @leofang!

**Comment by tirthasheshpatel** [comment]
I kept NumPy out since the DLPack API isn't public yet. But until it becomes public, pointing to the release notes is a good idea!

**Comment by leofang** [comment]
Right, NumPy folks kinda "hid" it from public to avoid being bothered, but they will eventually change it: https://github.com/numpy/numpy/issues/20743.

**Review by edgarriba — APPROVED** [review]

**Review by tqchen — APPROVED** [review]

**Comment by leofang** [comment]
Thanks all!

**Pull request merged**
